# Generated by Django 4.1.7 on 2023-05-08 00:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0009_profile_capacity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="technologies_used",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="profile", to="profiles.technology"
            ),
        ),
        migrations.CreateModel(
            name="ProfileTechnology",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.profile",
                    ),
                ),
                (
                    "technology",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.technology",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
