# Generated by Django 4.1.7 on 2023-05-08 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0010_alter_profile_technologies_used_profiletechnology"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="tech_stack",
            field=models.ManyToManyField(
                blank=True,
                related_name="profiles",
                through="profiles.ProfileTechnology",
                to="profiles.technology",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="technologies_used",
            field=models.ManyToManyField(blank=True, to="profiles.technology"),
        ),
    ]
