# Generated by Django 4.1.7 on 2023-05-08 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0011_profile_tech_stack_alter_profile_technologies_used"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="capacity",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name="profile",
            name="city",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name="profile",
            name="country",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name="profile",
            name="location",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name="profile",
            name="state",
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
