# Generated by Django 5.2.7 on 2025-10-18 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_alter_profile_capacity_alter_profile_city_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql='CREATE EXTENSION vector;',
            reverse_sql='DROP EXTENSION vector;',
        ),
    ]
