# Generated by Django 5.2.7 on 2025-10-18 07:00

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20251018_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, default=None, dimensions=1024, null=True),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='vector_index', opclasses=['vector_l2_ops']),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='vectors_index_2', opclasses=['vector_cosine_ops']),
        ),
    ]
