# Generated by Django 5.2.7 on 2025-10-18 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_profile_embedding_profile_vector_index_and_more'),
        ('djstripe', '0001_initial'),
    ]

    operations = [
    ]
