# Generated by Django 4.1.7 on 2023-03-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_customuser_twitter_handle_customuser_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outreachtemplate",
            name="cc_s",
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
