# Generated by Django 4.1.7 on 2023-03-25 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_outreachtemplate_cc_s"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="outreach",
            name="cc_s",
        ),
        migrations.RemoveField(
            model_name="outreach",
            name="subject_line",
        ),
        migrations.RemoveField(
            model_name="outreach",
            name="text",
        ),
        migrations.AddField(
            model_name="outreach",
            name="template",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outreach",
                to="users.outreachtemplate",
            ),
            preserve_default=False,
        ),
    ]
