# Generated by Django 5.2.7 on 2025-12-10 10:05

import secrets
from django.db import migrations, models


def generate_api_tokens(apps, schema_editor):
    CustomUser = apps.get_model('users', 'CustomUser')
    for user in CustomUser.objects.all():
        user.api_token = secrets.token_urlsafe(48)
        user.save(update_fields=['api_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_outreach_cc_s_remove_outreach_subject_line_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='api_token',
            field=models.CharField(
              blank=True,
              default='',
              help_text='API token for the user. Generated automatically when the user is created.',
              max_length=64,
            ),
        ),
        migrations.RunPython(generate_api_tokens, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='customuser',
            name='api_token',
            field=models.CharField(
              blank=True,
              db_index=True,
              default='',
              help_text='API token for the user. Generated automatically when the user is created.',
              max_length=64,
              unique=True,
            ),
        ),
    ]
