# Generated by Django 5.2.7 on 2025-12-10 11:41

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_api_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='api_token',
            field=models.CharField(blank=True, db_index=True, default=users.models.generate_api_token, help_text='API token for the user. Generated automatically when the user is created.', max_length=64, unique=True),
        ),
    ]
