# Generated by Django 4.2.1 on 2023-05-20 00:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import wagtail.fields


class Migration(migrations.Migration):

    replaces = [
        ("blog", "0001_initial"),
        ("blog", "0002_blogpage"),
        ("blog", "0003_blogpagegalleryimage"),
        ("blog", "0004_blogpagetag_blogpage_tags"),
        ("blog", "0005_blogtagindexpage"),
        ("blog", "0006_remove_blogpage_date_blogpage_date_created_and_more"),
        ("blog", "0007_alter_blogpage_icon_alter_blogpage_main_image"),
        ("blog", "0008_delete_blogpagegalleryimage"),
        ("blog", "0009_remove_blogtagindexpage_page_ptr_and_more"),
        ("blog", "0010_remove_blogpage_main_image"),
    ]

    initial = True

    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("wagtailcore", "0083_workflowcontenttype"),
        ("taggit", "0005_auto_20220424_2025"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("intro", wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="BlogPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("intro", models.CharField(max_length=250)),
                ("body", wagtail.fields.RichTextField(blank=True)),
                ("date_created", models.DateField(default=django.utils.timezone.now, verbose_name="Create Date")),
                ("date_modified", models.DateField(default=django.utils.timezone.now, verbose_name="Modified Date")),
                (
                    "icon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="wagtailimages.image"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
