# Generated by Django 4.2.1 on 2023-05-21 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("blog", "0002_blogpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpage",
            name="main_image",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="wagtailimages.image"
            ),
            preserve_default=False,
        ),
    ]
