# Generated by Django 4.2.1 on 2023-05-21 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("blog", "0004_alter_blogpage_icon_alter_blogpage_main_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="icon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="+", to="wagtailimages.image"
            ),
        ),
        migrations.AlterField(
            model_name="blogpage",
            name="main_image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="+", to="wagtailimages.image"
            ),
        ),
    ]
