# Generated by Django 4.2.1 on 2023-05-19 12:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("blog", "0005_blogtagindexpage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpage",
            name="date",
        ),
        migrations.AddField(
            model_name="blogpage",
            name="date_created",
            field=models.DateField(default=django.utils.timezone.now, verbose_name="Create Date"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="blogpage",
            name="date_modified",
            field=models.DateField(default=django.utils.timezone.now, verbose_name="Modified Date"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="blogpage",
            name="icon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="blogpage",
            name="main_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
