# Generated by Django 4.2.1 on 2023-05-19 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_blogpage_icon_alter_blogpage_main_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BlogPageGalleryImage",
        ),
    ]
