# Generated by Django 4.2.1 on 2023-05-19 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("blog", "0006_remove_blogpage_date_blogpage_date_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="icon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="+", to="wagtailimages.image"
            ),
        ),
        migrations.AlterField(
            model_name="blogpage",
            name="main_image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="+", to="wagtailimages.image"
            ),
        ),
    ]
