# Generated by Django 4.2.1 on 2023-05-19 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_delete_blogpagegalleryimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogtagindexpage",
            name="page_ptr",
        ),
        migrations.RemoveField(
            model_name="blogpage",
            name="tags",
        ),
        migrations.DeleteModel(
            name="BlogPageTag",
        ),
        migrations.DeleteModel(
            name="BlogTagIndexPage",
        ),
    ]
