# Generated by Django 4.2.1 on 2023-05-15 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("utils", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="utils.basemodel",
                    ),
                ),
                ("from_email", models.EmailField(max_length=254)),
                ("to_email", models.EmailField(max_length=254)),
                ("reply_to_email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=256)),
                ("body", models.TextField(blank=True)),
                ("replied", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
            bases=("utils.basemodel",),
        ),
    ]
