# Generated by Django 4.2.1 on 2023-05-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="asked_not_to_be_emailed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="email",
            name="failed",
            field=models.BooleanField(default=False),
        ),
    ]
